DataAPIToken: b0d3276763de9f9d3476908f03da05c664b1d057
DataAPIDataType: intraday
DataAPIFetchMethod:
DataAPIFreq: 1min
DataAPIStartDate: 2019-03-01
DataAPIEndDate: 2019-03-31
DataAPINumberOfObsPerDay: 1440
